services:
  db:
    container_name: mongo-container
    image: mongo:4
    restart: always # Caso o mongo caia, restarta automaticamente
    volumes: # Volumes mapeia pasta do PC para o Docker para persistir dados
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "yarn --prod && yarn add -D nodemon && yarn debug" # Trouxe o CMD yarn debug do Dockerfile para cá
    environment:
      - MONGO_URL=mongodb://db:27017/clean-node-api
    # Trouxe o COPY ./dist ./dist do Dockerfile para cá para garantir que o cache não vai impedir de atualizar o projeto
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/ # A barra no final indica que qualquer arquivo que mudar na dist também de trigger
      - ./package.json:/usr/src/clean-node-api/package.json
    ports: # Quando for expor portas aqui, pode retirar o EXPOSE 3333 do Dockerfile
      - "3333:3333"
      - "9222:9222"
    links:
      - db
    